/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radunkovic.racunalnaoprema.view;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import radunkovic.racunalnaoprema.controller.ObradaOdjel;
import radunkovic.racunalnaoprema.controller.ObradaOprema;
import radunkovic.racunalnaoprema.controller.ObradaOtpis;
import radunkovic.racunalnaoprema.model.Korisnik;
import radunkovic.racunalnaoprema.model.Odjel;
import radunkovic.racunalnaoprema.model.Oprema;
import radunkovic.racunalnaoprema.model.Otpis;
import radunkovic.racunalnaoprema.pomocno.RacunalnaOpremaException;

/**
 *
 * @author Ivan
 */
public class Otpisi extends javax.swing.JFrame {
    
    private ObradaOtpis obradaOtpis;
    private DecimalFormat format;
    private static DefaultComboBoxModel<Odjel> modelOdjel;
    private static DefaultComboBoxModel<Oprema> modelOprema;

    /**
     * Creates new form Otpisi
     */
    public Otpisi() {
        initComponents();
        obradaOtpis = new ObradaOtpis();
        NumberFormat nf = NumberFormat.getInstance(
                new Locale("hr")
        );
        format = (DecimalFormat) nf;
        format.applyPattern("#,###.00");
        
        DefaultComboBoxModel<Oprema> ms = new DefaultComboBoxModel<>();
        Oprema vp = new Oprema();
        vp.setNaziv("Odaberite opremu");
        vp.setMacadresa("");
        ms.addElement(vp);
        new ObradaOprema().getLista().forEach((s) -> {
            ms.addElement(s);
        });
        cbOprema.setModel(ms);
        
        DefaultComboBoxModel<Odjel> a = new DefaultComboBoxModel<>();
        Odjel od = new Odjel();
        od.setNaziv("Odaberite odjel");
        a.addElement(od);
        new ObradaOdjel().getLista().forEach((s) -> {
            a.addElement(s);
        });
        cbOdjel.setModel(a);
        
        
        ucitajPodatke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstOtpisi = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtVrijednost = new javax.swing.JTextField();
        chbAktivno = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cbOdjel = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbOprema = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Otpis");

        lstOtpisi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstOtpisi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOtpisiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOtpisi);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Vrijednost");

        txtVrijednost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        chbAktivno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        chbAktivno.setText("Aktivno");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Odjel");

        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPromjena.setText("Promjena");
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnBrisanje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ocisti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Oprema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnDodaj)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPromjena)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBrisanje))
                        .addComponent(cbOdjel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbOprema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtVrijednost, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbAktivno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVrijednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbAktivno))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbOprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjena)
                            .addComponent(btnBrisanje))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstOtpisiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOtpisiValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        Otpis s = lstOtpisi.getSelectedValue();
        if (s == null) {
            return;
        }
        
        try {
            txtVrijednost.setText(format.format(s.getVrijednost()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        chbAktivno.setSelected(s.isAktivno());

        modelOdjel = (DefaultComboBoxModel<Odjel>) cbOdjel.getModel();
        for (int i = 0; i < modelOdjel.getSize(); i++) {
            if (modelOdjel.getElementAt(i).getSifra() == s.getOdjel().getSifra()) {
                cbOdjel.setSelectedIndex(i);
                break;
            }
        }
        
        modelOprema = (DefaultComboBoxModel<Oprema>) cbOprema.getModel();
        for (int i = 0; i < modelOprema.getSize(); i++) {
            if (modelOprema.getElementAt(i).getSifra() == s.getOprema().getSifra()) {
                cbOprema.setSelectedIndex(i);
                break;
            }
        }

    }//GEN-LAST:event_lstOtpisiValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Otpis s = new Otpis();

        preuzmiVrijednosti(s);

        try {
            obradaOtpis.spremi(s);
        } catch (RacunalnaOpremaException e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
            return;
        }

        ucitajPodatke();
        ocistiPolja();

        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
        Otpis s = lstOtpisi.getSelectedValue();

        if (s == null) {
            JOptionPane.showConfirmDialog(null, "Prvo odaberite otpis");
        }

        preuzmiVrijednosti(s);

        try {
            obradaOtpis.spremi(s);
        } catch (RacunalnaOpremaException e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
            return;
        }

        ucitajPodatke();
        ocistiPolja();

        
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        Otpis s = lstOtpisi.getSelectedValue();

        if (s == null) {
            JOptionPane.showConfirmDialog(null, "Prvo odaberite otpis");
        }

        try {
            obradaOtpis.obrisi(s);
            ucitajPodatke();
            ocistiPolja();
        } catch (RacunalnaOpremaException ex) {
            JOptionPane.showMessageDialog(null, "Ne mogu obrisati");
        }
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ocistiPolja();
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JComboBox<Odjel> cbOdjel;
    private javax.swing.JComboBox<Oprema> cbOprema;
    private javax.swing.JCheckBox chbAktivno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Otpis> lstOtpisi;
    private javax.swing.JTextField txtVrijednost;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {
        DefaultListModel<Otpis> k = new DefaultListModel<>();
        for (Otpis m : obradaOtpis.getLista()) {
            k.addElement(m);
        }
        lstOtpisi.setModel(k);
    }

    private void ocistiPolja() {
        txtVrijednost.setText("");
        cbOdjel.setSelectedIndex(0);
        cbOprema.setSelectedIndex(0);
        chbAktivno.setSelected(false);
        
    }

    private void preuzmiVrijednosti(Otpis s) {
        try {
            s.setVrijednost(
                    new BigDecimal(
                            format.parse(txtVrijednost.getText()).floatValue()
                    )
            );
        } catch (Exception e) {
           s.setVrijednost(BigDecimal.ZERO);
           txtVrijednost.setText("0");
        };
        s.setAktivno(chbAktivno.isSelected());
        s.setOdjel((Odjel)cbOdjel.getSelectedItem());
        s.setOprema((Oprema)cbOprema.getSelectedItem());
    }
}
